<?php

namespace Container6iiJUeb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KWB0M9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kW_B0M9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kW_B0M9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManagerInterface' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'succesRepository' => ['privates', 'App\\Repository\\SuccesRepository', 'getSuccesRepositoryService', true],
        ], [
            'entityManagerInterface' => '?',
            'succesRepository' => 'App\\Repository\\SuccesRepository',
        ]);
    }
}
