<?php

namespace Container6iiJUeb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IJHRmtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iJ_HRmt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iJ_HRmt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'succesRepository' => ['privates', 'App\\Repository\\SuccesRepository', 'getSuccesRepositoryService', true],
        ], [
            'succesRepository' => 'App\\Repository\\SuccesRepository',
        ]);
    }
}
