<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6iiJUeb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6iiJUeb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6iiJUeb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6iiJUeb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6iiJUeb\App_KernelDevDebugContainer([
    'container.build_hash' => '6iiJUeb',
    'container.build_id' => '8a19279a',
    'container.build_time' => 1709495148,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6iiJUeb');
