# config/routes/annotations.yaml
controllers:
    resource: ../src/Controller/
    type: annotation

app_taches_favorites:
    path: '/taches/favorites'
    controller: 'App\Controller\TachesController::favorites'
    methods: ['GET']